---
- hosts: all
  gather_facts: False
  vars:
    ansible_become: True

  tasks:
  - selinux:
      state: disabled

  - name: Add Zabbix repo
    yum:
      name: https://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
      state: present

  - name: Install Zabbix
    yum:
      pkg: 
      - unzip
      - postgresql-server
      - python-psycopg2
      - libsemanage-python
      - zabbix-server-pgsql
      - zabbix-web-pgsql
      - zabbix-agent
      - zabbix-java-gateway
      state: present

  - name: Initiate database
    command: service postgresql initdb
    args:
      creates: /var/lib/pgsql/data/postgresql.conf

  - name: Configure PostgreSQL authentication
    lineinfile:
      dest: /var/lib/pgsql/data/pg_hba.conf
      regexp: '^host +all +all +::1/128'
      line: 'host    all             all             ::1/128            trust'

  - name: Configure PostgreSQL authentication
    lineinfile:
      dest: /var/lib/pgsql/data/pg_hba.conf
      regexp: '^local +all +all'
      line: 'local   all             all                                     trust'

  - name: Enable PostgreSQL
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - postgresql

  - name: Configure PostgreSQL user
    postgresql_user:
      name: zabbix
      password: zabbix42
      role_attr_flags: CREATEDB,NOSUPERUSER

  - name: Create PostgreSQL database
    postgresql_db:
      name: zabbix
      owner: zabbix

  - name: Create Database Schema
    shell: zcat /usr/share/doc/zabbix-server-pgsql-3.2.*/create.sql.gz | psql -U zabbix zabbix

  - name: Configure PHP
    lineinfile:
      dest: /etc/httpd/conf.d/zabbix.conf
      regexp: php_value date.timezone
      line: php_value date.timezone America/Sao_Paulo

  - name: Configure Zabbix
    ini_file:
      dest: /etc/zabbix/zabbix_server.conf
      section: null
      option: "{{ item.key }}"
      value: "{{ item.value }}"
    with_dict:
      JavaGateway: localhost
      StartJavaPollers: 1

  - name: Enable Zabbix Services
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - httpd
      - zabbix-server
      - zabbix-agent
      - zabbix-java-gateway

  - name: Check JBoss downloaded
    stat:
      path: /vagrant/jboss-eap-6.4.0.zip
    register: jboss

  - name: Download JBoss
    shell: |
      curl -Lo /vagrant/jboss-eap-6.4.0.zip https://www.dropbox.com/s/1lehk7mu5i69gml/jboss-eap-6.4.0.zip?dl=0
    when: jboss.stat.exists == False

  - name: Install JBoss EAP dependencies
    yum:
      pkg:
      - java-1.8.0-openjdk-devel
      state: present

  - name: Extract JBoss EAP files
    unarchive:
      src: /vagrant/jboss-eap-6.4.0.zip
      dest: /usr/src

  - name: Check Zabbix Source downloaded
    stat:
      path: /vagrant/zabbix-3.2.7.tgz
    register: zabbix

  - name: Download Zabbix Source
    shell: |
      curl -Lo /vagrant/zabbix-3.2.7.tgz 'https://downloads.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/3.2.7/zabbix-3.2.7.tar.gz?r=&ts=1503001091&use_mirror=ufpr'
    when: zabbix.stat.exists == False

  - name: Extract Zabbix Source
    unarchive:
      src: /vagrant/zabbix-3.2.7.tgz
      dest: /usr/src

  - name: Compile Zabbix Java Gateway
    shell: /vagrant/src/build.sh

  - name: Configure Zabbix Java Gateway
    ini_file:
      dest: /etc/zabbix/zabbix_java_gateway.conf
      no_extra_spaces: yes
      section: null
      option: "{{ item.key }}"
      value: "{{ item.value }}"
    with_dict:
      GATEWAY_HOME: "/usr/local/sbin/zabbix_java"
    notify:
      restart gateway

  handlers:
    - name: restart gateway
      service:
        name: zabbix-java-gateway
        state: restarted